FROM python:3.10.11-alpine3.17

RUN apk add --no-cache curl

RUN pip3 install --no-cache-dir aiogram==3.0.0b6

RUN pip3 install  --no-cache-dir environs==9.5.0

COPY ./ /app

WORKDIR /app

# Use it, if your ffmpeg do not access for run
#RUN chmod +x /app/services/ffmpeg_linux/ffmpeg

EXPOSE 8080

# This option for google cloud run services
CMD ["sh",  "-c", "python3 bot_polling_run.py & python3 -m http.server 8080"]

# Use it, if you do not need check port for alive container
#CMD ["python3", "python3 bot_polling_run.py"]
